import type { NewSubscriptionPriceMigrationStorageValues } from '../../mappers/subscription-price-migration.mapper';
import { fromDate } from '../mappers';

export function subscriptionPriceMigrationCreateRow(
  data: NewSubscriptionPriceMigrationStorageValues,
): Record<string, unknown> {
  return {
    tenant_key: data.tenantKey,
    subscription_id: data.subscriptionId,
    primary_item_id: data.primaryItemId,
    active_subscription_id: data.activeSubscriptionId,
    source_price_id: data.sourcePriceId,
    target_price_id: data.targetPriceId,
    source_price: data.sourcePrice,
    target_price: data.targetPrice,
    current_items: data.currentItems,
    proposed_items: data.proposedItems,
    effective_timing: data.effectiveTiming,
    effective_at: fromDate(data.effectiveAt),
    proration_policy: data.prorationPolicy,
    payment_failure_policy: data.paymentFailurePolicy,
    immediate_adjustment: data.immediateAdjustment,
    next_renewal: data.nextRenewal,
    current_renewal_date: fromDate(data.currentRenewalDate),
    warnings: data.warnings,
    provider_limitations: data.providerLimitations,
    provider_evidence: data.providerEvidence,
    preview_token: data.previewToken,
    request_hash: data.requestHash,
    calculated_at: data.calculatedAt.toISOString(),
    expires_at: data.expiresAt.toISOString(),
    provider_binding_id: data.providerBindingId,
    status: data.status,
    attempt_count: data.attemptCount,
    execution_token: null,
    failure_code: null,
    failure_message: null,
    scheduled_at: null,
    execution_started_at: null,
    applied_at: null,
    failed_at: null,
    reconciliation_required_at: null,
    reconciliation_outcome: null,
    reconciliation_evidence_reference: null,
    reconciliation_resolved_at: null,
    reconciliation_observation_evidence_reference: null,
    reconciliation_observed_at: null,
    cancelled_at: null,
  };
}
