export type ProviderCapability =
  | 'checkout'
  | 'charges'
  | 'authorize'
  | 'capture'
  | 'void'
  | 'subscriptions'
  | 'trials'
  | 'refunds'
  | 'coupons'
  | 'billingPortal'
  | 'meteredBilling'
  | 'invoicePdf'
  | 'webhooks'
  | 'customers'
  | 'paymentMethods'
  | 'paymentMethodSetup'
  | 'disputes'
  | 'payouts'
  | 'webhookEndpointManagement'
  | 'catalog'
  | 'catalogRead'
  | 'catalogLifecycle'
  | 'catalogIdempotency'
  | 'catalogProductCreate'
  | 'catalogProductUpdate'
  | 'catalogProductArchive'
  | 'catalogProductReactivate'
  | 'catalogPriceCreate'
  | 'catalogPriceUpdate'
  | 'catalogPriceArchive'
  | 'catalogPriceReactivate'
  | 'priceLookupKeys';

export type ProviderCapabilityValue = ProviderCapability | (string & {});

export type ProviderCapabilities = ReadonlySet<ProviderCapabilityValue>;
