export interface PrismaSubscriptionRow {
  id: string;
  tenantId: string | null;
  tenantKey: string;
  customerId: string;
  name: string;
  provider: string | null;
  providerSubscriptionId: string | null;
  status: string;
  priceId: string | null;
  quantity: number;
  canonicalPriceId: string | null;
  acceptedCurrency: string | null;
  acceptedUnitAmount: bigint | null;
  acceptedInterval: string | null;
  acceptedIntervalCount: number | null;
  acceptedQuantity: number | null;
  collectionResponsibility: string;
  creationSource: string | null;
  trialEndsAt: Date | null;
  endsAt: Date | null;
  currentPeriodStart: Date | null;
  currentPeriodEnd: Date | null;
  providerSyncedAt: Date | null;
  scheduledChangeAction: string | null;
  scheduledChangeEffectiveAt: Date | null;
  scheduledResumeAt: Date | null;
  resumeBillingPolicy: string | null;
  paymentCollectionPauseBehavior: string | null;
  paymentCollectionResumesAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}
