import type { ProviderCapabilities } from '../../../domain/dtos/capabilities.dto';

export function stripeCapabilities(): ProviderCapabilities {
  return new Set([
    'checkout',
    'charges',
    'authorize',
    'capture',
    'void',
    'subscriptions',
    'trials',
    'refunds',
    'coupons',
    'billingPortal',
    'invoicePdf',
    'webhooks',
    'customers',
    'paymentMethods',
    'paymentMethodSetup',
    'disputes',
    'payouts',
    'webhookEndpointManagement',
    'catalog',
    'catalogRead',
    'catalogLifecycle',
    'catalogIdempotency',
    'catalogProductCreate',
    'catalogProductUpdate',
    'catalogProductArchive',
    'catalogProductReactivate',
    'catalogPriceCreate',
    'catalogPriceUpdate',
    'catalogPriceArchive',
    'catalogPriceReactivate',
    'priceLookupKeys',
  ]);
}
